In [72]:
import pandas as pd
import altair as alt

## CSV Trick
I made a little trick for CSV file - just deleted its first line right in file. Hope, it`s okay :)

In [77]:
df = pd.read_csv('./GLB.Ts_dSST.csv')
df.head()

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,J-D,D-N,DJF,MAM,JJA,SON
0,1880,-0.29,-0.18,-0.11,-0.19,-0.11,-0.23,-0.21,-0.09,-0.16,-0.23,-0.20,-0.23,-0.19,***,***,-0.14,-0.18,-0.20
1,1881,-0.15,-0.17,0.04,0.04,0.02,-0.20,-0.06,-0.02,-0.13,-0.20,-0.21,-0.10,-0.10,-.11,-.18,0.03,-0.09,-0.18
2,1882,0.15,0.15,0.04,-0.18,-0.16,-0.26,-0.20,-0.05,-0.10,-0.24,-0.16,-0.24,-0.10,-.09,.06,-0.10,-0.17,-0.17
3,1883,-0.31,-0.39,-0.13,-0.17,-0.20,-0.12,-0.08,-0.15,-0.20,-0.14,-0.22,-0.16,-0.19,-.20,-.31,-0.16,-0.12,-0.19
4,1884,-0.15,-0.08,-0.37,-0.42,-0.36,-0.40,-0.34,-0.26,-0.27,-0.24,-0.30,-0.28,-0.29,-.28,-.13,-0.39,-0.34,-0.27

## Transform data

Find average for each year

In [78]:
new_data = []
columns = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

for index, row in df.iterrows():
  sum = 0
  for month in columns:
    sum += row[month]
  new_data.append([row['Year'], round(sum / 12, 3)])

new_df = pd.DataFrame(new_data, columns = ['Year', 'Average'])

In [79]:
new_df.head()

   Year  Average
0  1880   -0.186
1  1881   -0.095
2  1882   -0.104
3  1883   -0.189
4  1884   -0.289

In [83]:
# Main chart settings
chart = alt.Chart(new_df).mark_point(
        color = '#5D5956',
        fill = '#F26C08',
        size = 100,
        opacity = 1,
        strokeWidth = 1).encode(
    x = alt.X(field='Year',
              title = 'Year',
              type = 'quantitative',
              scale = alt.Scale(
                  zero = False,
            ),
            axis = alt.Axis(
             format = 'k',
             tickCount = 15,
             )),
    y = alt.Y(field = 'Average',
              title='Average temperature per year (°C)',
              type = 'quantitative',
              scale = alt.Scale(
                  zero = False
              ),
            axis = alt.Axis(
             tickCount = 10,

             )),
    tooltip = [
        alt.Tooltip(field = 'Year', type = 'nominal'),
        alt.Tooltip(field = 'Average', title='Temperature (°C)', type = 'nominal')
    ]
)

# Zero line
line = alt.Chart(pd.DataFrame({'y': [0]})).mark_rule(color='#989898').encode(y='y')

# 1 Title line
title1 = alt.Chart({'values':[{'x': 1882, 'y': 0.95}]}).mark_text(
    text='Annual Global Surface Temperature,',
    align='left',
    fontSize=15,
    fontWeight=700
).encode(x='x:Q', y='y:Q')

# 2 Title line
title2 = alt.Chart({'values':[{'x': 1882, 'y': 0.89}]}).mark_text(
    text='Relative to Late 19th Century Average',
    align='left',
    fontSize=15,
    fontWeight=700
).encode( x='x:Q', y='y:Q')

# 'Hotter' text
hotter_text = alt.Chart({'values':[{'x': 2019, 'y': 0.05}]}).mark_text(
    align='right',
    text='HOTTER THAN THE 1880-1899 AVERAGE',
    fontWeight=500
).encode(x='x:Q', y='y:Q')

# 'Colder' text
colder_text = alt.Chart({'values':[{'x': 2019, 'y': -0.05}]}).mark_text(
    align='right',
    text='COLDER',
    fontWeight=500
).encode(x='x:Q', y='y:Q')

# Come together... right now!
alt.layer(chart, line, colder_text, hotter_text, title1, title2).properties(
    width = 950, height = 500, background = '#F9F9F9', padding = 25
    ).configure_axis(domain=False)

alt.LayerChart(...)

## Issues:

- didn`t find solution for how to format Y ticks into Celsius format
- not sure about texts and if it is right way to use them (like 'Hotter than...' and title)
- no labels for dots (as 1944 on example image) but there are tooltips with year and temperature